166.62.127.180 - - [15/Jul/2017 21:33:12] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [15/Jul/2017 21:33:19] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [15/Jul/2017 21:33:24] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [15/Jul/2017 21:37:49] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
[36mI    db          Connecting to database...[0m
[36mI    db          Establishing connection...[0m
[32mC    db          Connected to database.[0m
[36mI    db          Setting up server...[0m
Traceback (most recent call last):
  File "./server.py", line 147, in <module>
    httpd = SocketServer.TCPServer(('', PORT), RequestHandler)
  File "/usr/local/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
