98.228.49.55 - - [29/Jun/2017 22:00:09] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
98.228.49.55 - - [29/Jun/2017 22:00:17] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
98.228.49.55 - - [29/Jun/2017 22:00:35] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
98.228.49.55 - - [29/Jun/2017 22:02:02] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
98.228.49.55 - - [29/Jun/2017 22:03:28] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
98.228.49.55 - - [29/Jun/2017 22:03:37] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
172.58.83.193 - - [29/Jun/2017 23:08:55] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
[36mI    db          Connecting to database...[0m
[36mI    db          Establishing connection...[0m
[32mC    db          Connected to database.[0m
[36mI    db          Setting up server...[0m
[32mC    db          Setup done..[0m
[36mI    db          Serve...[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3371)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3370)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3372)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3374)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3737)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
[36mI    db          Connecting to database...[0m
[36mI    db          Establishing connection...[0m
[32mC    db          Connected to database.[0m
[36mI    db          Setting up server...[0m
Traceback (most recent call last):
  File "./server.py", line 137, in <module>
    httpd = SocketServer.TCPServer(('', PORT), RequestHandler)
  File "/usr/local/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3738)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 3739)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4230)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4231)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4232)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4248)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4249)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4251)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4253)
----------------------------------------
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
----------------------------------------
Exception happened during processing of request from ('75.132.83.98', 4257)
----------------------------------------
[36mI    conn        Connection established.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./server.py", line 117, in do_GET
    res = lookup_course(db, subject, code, suffix)
  File "/home/uicourses/db2json/dbutil.py", line 156, in lookup_course
    cur.execute(qry, (subject.upper(), code.upper(), suffix.upper()))
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
[36mI    db          Connecting to database...[0m
[36mI    db          Establishing connection...[0m
[32mC    db          Connected to database.[0m
[36mI    db          Setting up server...[0m
Traceback (most recent call last):
  File "./server.py", line 137, in <module>
    httpd = SocketServer.TCPServer(('', PORT), RequestHandler)
  File "/usr/local/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
98.228.49.55 - - [30/Jun/2017 20:10:05] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
75.132.83.98 - - [01/Jul/2017 00:35:07] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 00:45:25] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 00:46:08] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 00:46:10] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 00:46:27] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 00:46:43] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 00:46:44] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
[36mI    db          Connecting to database...[0m
[36mI    db          Establishing connection...[0m
[32mC    db          Connected to database.[0m
[36mI    db          Setting up server...[0m
[32mC    db          Setup done..[0m
[36mI    db          Serve...[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api         Looking up: cs 374 [0m
[36mI    api         Lookup done.[0m
[36mI    api         Sending response...[0m
[36mI    conn        Header sent.[0m
[36mI    conn        Sending data...[0m
[32mC    conn        Data sent.[0m
[32mC    conn        Connection closed.[0m
[36mI    conn        Connection established.[0m
[36mI    api         request: /dbapi?subject=cs&code=374&key=mykey[0m
[36mI    api         Validating parameters...[0m
[36mI    api         Filters validated.[0m
[36mI    api      166.62.127.180 - - [01/Jul/2017 00:47:50] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
75.132.83.98 - - [01/Jul/2017 01:07:22] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:08:20] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:08:45] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:10:25] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:10:57] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:11:23] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:11:32] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
75.132.83.98 - - [01/Jul/2017 01:16:47] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:17:29] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:17:50] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
75.132.83.98 - - [01/Jul/2017 01:20:37] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:20:51] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:20:54] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
166.62.127.180 - - [01/Jul/2017 01:23:12] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
Traceback (most recent call last):
  File "./server.py", line 26, in <module>
    from dbutil import *
  File "/home/uicourses/db2json/dbutil.py", line 195
    except:
         ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "./server.py", line 26, in <module>
    from dbutil import *
  File "/home/uicourses/db2json/dbutil.py", line 195
    except:
         ^
SyntaxError: invalid syntax
166.62.127.180 - - [01/Jul/2017 01:57:23] "GET /dbapi?subject=cs&code=374&key=mykey HTTP/1.1" 200 -
[36mI    db          Connecting to database...[0m
[36mI    db          Establishing connection...[0m
[32mC    db          Connected to database.[0m
[36mI    db          Setting up server...[0m
Traceback (most recent call last):
  File "./server.py", line 137, in <module>
    httpd = SocketServer.TCPServer(('', PORT), RequestHandler)
  File "/usr/local/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
